const $=id=>document.getElementById(id);const today=()=>new Date().toISOString().slice(0,10);
let sb=null,currentUser=null,players=[],sessions=[],attendanceRows=[],ratingRows=[],lineups=[],matches=[],liveMatches=[],currentLineupAssignments={},activePosition=null,dragSourcePosition=null,moveSourcePosition=null,suppressPickerUntil=0;
let liveMatch=null,liveTimer=null;
const FORMATIONS={"4-3-3":[{pos:"GK",x:50,y:91},{pos:"LB",x:18,y:73},{pos:"LCB",x:38,y:75},{pos:"RCB",x:62,y:75},{pos:"RB",x:82,y:73},{pos:"LCM",x:32,y:52},{pos:"CM",x:50,y:48},{pos:"RCM",x:68,y:52},{pos:"LW",x:22,y:25},{pos:"ST",x:50,y:17},{pos:"RW",x:78,y:25}],"4-2-3-1":[{pos:"GK",x:50,y:91},{pos:"LB",x:18,y:73},{pos:"LCB",x:38,y:75},{pos:"RCB",x:62,y:75},{pos:"RB",x:82,y:73},{pos:"LDM",x:38,y:58},{pos:"RDM",x:62,y:58},{pos:"LW",x:22,y:36},{pos:"AM",x:50,y:34},{pos:"RW",x:78,y:36},{pos:"ST",x:50,y:17}],"4-4-2":[{pos:"GK",x:50,y:91},{pos:"LB",x:18,y:73},{pos:"LCB",x:38,y:75},{pos:"RCB",x:62,y:75},{pos:"RB",x:82,y:73},{pos:"LM",x:20,y:48},{pos:"LCM",x:40,y:50},{pos:"RCM",x:60,y:50},{pos:"RM",x:80,y:48},{pos:"LST",x:40,y:20},{pos:"RST",x:60,y:20}],"3-5-2":[{pos:"GK",x:50,y:91},{pos:"LCB",x:30,y:75},{pos:"CB",x:50,y:77},{pos:"RCB",x:70,y:75},{pos:"LWB",x:15,y:52},{pos:"LCM",x:36,y:52},{pos:"CM",x:50,y:47},{pos:"RCM",x:64,y:52},{pos:"RWB",x:85,y:52},{pos:"LST",x:42,y:20},{pos:"RST",x:58,y:20}],"3-4-3":[{pos:"GK",x:50,y:91},{pos:"LCB",x:30,y:75},{pos:"CB",x:50,y:77},{pos:"RCB",x:70,y:75},{pos:"LWB",x:18,y:52},{pos:"LCM",x:42,y:52},{pos:"RCM",x:58,y:52},{pos:"RWB",x:82,y:52},{pos:"LW",x:23,y:23},{pos:"ST",x:50,y:17},{pos:"RW",x:77,y:23}],"3-4-2-1":[{pos:"GK",x:50,y:91},{pos:"LCB",x:30,y:75},{pos:"CB",x:50,y:77},{pos:"RCB",x:70,y:75},{pos:"LWB",x:18,y:52},{pos:"LCM",x:42,y:52},{pos:"RCM",x:58,y:52},{pos:"RWB",x:82,y:52},{pos:"LAM",x:40,y:32},{pos:"RAM",x:60,y:32},{pos:"ST",x:50,y:16}],"4-1-4-1":[{pos:"GK",x:50,y:91},{pos:"LB",x:18,y:73},{pos:"LCB",x:38,y:75},{pos:"RCB",x:62,y:75},{pos:"RB",x:82,y:73},{pos:"DM",x:50,y:60},{pos:"LM",x:20,y:42},{pos:"LCM",x:40,y:43},{pos:"RCM",x:60,y:43},{pos:"RM",x:80,y:42},{pos:"ST",x:50,y:17}],"5-3-2":[{pos:"GK",x:50,y:91},{pos:"LWB",x:14,y:70},{pos:"LCB",x:32,y:76},{pos:"CB",x:50,y:78},{pos:"RCB",x:68,y:76},{pos:"RWB",x:86,y:70},{pos:"LCM",x:35,y:50},{pos:"CM",x:50,y:47},{pos:"RCM",x:65,y:50},{pos:"LST",x:42,y:20},{pos:"RST",x:58,y:20}]};
const BENCH_COUNT=7;
function okConfig(){return typeof SUPABASE_URL==='string'&&SUPABASE_URL.startsWith('https://')&&!SUPABASE_URL.includes('PASTE_')&&!SUPABASE_ANON_KEY.includes('PASTE_')}
function msg(t){$('authMessage').textContent=t||''}function esc(s){return String(s||'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
function showApp(){$('authView').classList.add('hidden');$('appView').classList.remove('hidden');$('logoutBtn').classList.remove('hidden')}function showAuth(){$('authView').classList.remove('hidden');$('appView').classList.add('hidden');$('logoutBtn').classList.add('hidden')}
function requireUser(){if(!currentUser){alert('Please log in first.');return false}return true}function loading(id,on,txt='Saving...'){const b=$(id);if(!b)return;if(on){b.dataset.t=b.textContent;b.textContent=txt;b.disabled=true}else{b.textContent=b.dataset.t||b.textContent;b.disabled=false}}
function nameOf(id){const p=players.find(x=>x.id===id);return p?`${p.first_name||''} ${p.last_name||''}`.trim()||'Unnamed player':'Unassigned'}
function posText(p){const a=Array.isArray(p.positions)&&p.positions.length?p.positions:(p.position?[p.position]:[]);return a.length?a.join(', '):'No position'}
function playerOptions(sel='',excludeIds=new Set()){return '<option value="">Select player</option>'+players.filter(p=>p.id===sel||!excludeIds.has(p.id)).map(p=>`<option value="${p.id}" ${p.id===sel?'selected':''}>${esc(nameOf(p.id))} — ${esc(posText(p))}</option>`).join('')}
function starterIds(exceptPosition=''){return new Set(Object.entries(currentLineupAssignments||{}).filter(([pos,id])=>id&&pos!==exceptPosition).map(([,id])=>id))}
function usedPlayerIds(exceptPosition=''){const used=starterIds(exceptPosition);selectedBenchIds().forEach(id=>used.add(id));return used}
function removePlayerFromOtherSlots(playerId,currentPosition=''){Object.keys(currentLineupAssignments||{}).forEach(pos=>{if(pos!==currentPosition&&currentLineupAssignments[pos]===playerId)delete currentLineupAssignments[pos]})}
function formationOrder(f){return (FORMATIONS[f]||[]).map(n=>n.pos)}
function orderedLineupText(lineup,formation){const order=formationOrder(formation),obj=lineup||{};const ordered=order.filter(pos=>obj[pos]).map(pos=>`${pos}: ${nameOf(obj[pos])}`);const extra=Object.keys(obj).filter(pos=>!order.includes(pos)).map(pos=>`${pos}: ${nameOf(obj[pos])}`);return ordered.concat(extra)}
function selectedBenchIds(){return [...document.querySelectorAll('.bench-select')].map(s=>s.value).filter(Boolean)}
function multiVals(el){return [...el.selectedOptions].map(o=>o.value).filter(Boolean)}
function setDefaults(){['sessionDate','attendanceDate','ratingsDate','matchDate','lineupDate'].forEach(id=>{if($(id)&&!$(id).value)$(id).value=today()});$('formationSelect').innerHTML=Object.keys(FORMATIONS).map(f=>`<option>${f}</option>`).join('')}
async function init(){setDefaults();if(!okConfig()){$('setupWarning').classList.remove('hidden');['signUpBtn','loginBtn'].forEach(id=>$(id).disabled=true);msg('Backend not configured yet.');renderPitchDiagram();return}sb=supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY);const {data}=await sb.auth.getSession();currentUser=data.session?.user||null;sb.auth.onAuthStateChange(async(_e,session)=>{currentUser=session?.user||null;if(currentUser){showApp();await loadAll()}else showAuth()});if(currentUser){showApp();await loadAll()}else showAuth();renderPitchDiagram()}
async function signUp(){const email=$('email').value.trim(),password=$('password').value.trim();if(!email||!password)return msg('Enter email and password.');if(password.length<6)return msg('Password must be at least 6 characters.');loading('signUpBtn',true,'Creating...');const {data,error}=await sb.auth.signUp({email,password});loading('signUpBtn',false);if(error)return msg(error.message);if(data.session?.user){currentUser=data.session.user;showApp();await loadAll()}else msg('Account created. Check email or disable email confirmation in Supabase for testing.')}
async function login(){const email=$('email').value.trim(),password=$('password').value.trim();if(!email||!password)return msg('Enter email and password.');loading('loginBtn',true,'Logging in...');const {data,error}=await sb.auth.signInWithPassword({email,password});loading('loginBtn',false);if(error)return msg(error.message);currentUser=data.user;showApp();await loadAll()}
async function logout(){await sb.auth.signOut();currentUser=null;showAuth()}
async function saveProfile(){if(!requireUser())return;const payload={user_id:currentUser.id,coach_name:$('coachName').value.trim(),club:$('coachClub').value.trim(),age_group:$('coachAgeGroup').value.trim()};loading('saveProfileBtn',true);const {error}=await sb.from('profiles').upsert(payload,{onConflict:'user_id'});loading('saveProfileBtn',false);if(error)return alert(error.message);await loadProfile();alert('Profile saved.')}
async function loadProfile(){const {data,error}=await sb.from('profiles').select('*').eq('user_id',currentUser.id).maybeSingle();if(error)return console.error(error);$('coachName').value=data?.coach_name||'';$('coachClub').value=data?.club||'';$('coachAgeGroup').value=data?.age_group||'';$('welcomeTitle').textContent=data?.coach_name?`Welcome, ${data.coach_name}`:'Welcome coach'}
async function addPlayer(){if(!requireUser())return;const first=$('playerFirst').value.trim(),last=$('playerLast').value.trim(),positions=multiVals($('playerPositions'));if(!first&&!last)return alert('Add at least a first name or surname.');if(!positions.length)return alert('Select at least one position.');loading('addPlayerBtn',true,'Adding...');const {error}=await sb.from('players').insert({user_id:currentUser.id,first_name:first,last_name:last,positions});loading('addPlayerBtn',false);if(error)return alert(error.message);$('playerFirst').value='';$('playerLast').value='';[...$('playerPositions').options].forEach(o=>o.selected=false);await loadAll()}
async function deleteRow(table,id){if(!requireUser()||!confirm('Delete this item?'))return;const {error}=await sb.from(table).delete().eq('id',id).eq('user_id',currentUser.id);if(error)return alert(error.message);await loadAll()}
async function fetchPlayers(){const {data,error}=await sb.from('players').select('*').eq('user_id',currentUser.id).order('created_at',{ascending:false});if(error)throw error;players=data||[]}
function playerStats(pid){const at=attendanceRows.filter(r=>r.player_id===pid),att=at.filter(r=>r.present).length;const starts=lineups.filter(l=>Object.values(l.lineup||{}).includes(pid)).length;const bench=lineups.filter(l=>Array.isArray(l.bench)&&l.bench.includes(pid)).length;const rs=ratingRows.filter(r=>r.player_id===pid&&r.score);const avg=rs.length?(rs.reduce((a,r)=>a+Number(r.score),0)/rs.length).toFixed(1):'-';return{att,miss:at.length-att,starts,played:starts+bench,avg,rs,at}}
function renderPlayers(){$('playersList').innerHTML=players.map(p=>{const st=playerStats(p.id);return `<div class="item"><div class="player-row" onclick="togglePlayer('${p.id}')"><div><b>${esc(nameOf(p.id))}</b><br><small>${esc(posText(p))}</small></div><span class="badge">Tap profile</span></div><div id="player-${p.id}" class="detail hidden"><div class="mini-grid"><div class="mini"><b>${st.att}</b><span>Training attended</span></div><div class="mini"><b>${st.played}</b><span>Games played/selected</span></div><div class="mini"><b>${st.starts}</b><span>Games started</span></div><div class="mini"><b>${st.avg}</b><span>Avg rating</span></div></div><h4>Recent attendance</h4>${st.at.slice(0,6).map(r=>`<p>${r.attendance_date} • ${esc(r.note||'Training')} • <b>${r.present?'Present':'Absent'}</b></p>`).join('')||'<p>No attendance yet.</p>'}<h4>Recent ratings</h4>${st.rs.slice(0,5).map(r=>`<p>${r.rating_date} • ${esc(r.context||'Rating')} • <b>${r.score}/10</b>${r.note?' — '+esc(r.note):''}</p>`).join('')||'<p>No ratings yet.</p>'}</div><div class="item-row"><small>Player record</small><button class="danger" onclick="deleteRow('players','${p.id}')">Delete</button></div></div>`}).join('')||'<p class="muted">No players yet.</p>';renderAttendanceForm();renderRatingsForm();renderPitchDiagram()}
function togglePlayer(id){document.querySelectorAll('.detail[id^="player-"]').forEach(x=>{if(x.id!==`player-${id}`)x.classList.add('hidden')});$(`player-${id}`).classList.toggle('hidden')}
async function saveSession(){if(!requireUser())return;const title=$('sessionTitle').value.trim();if(!title)return alert('Session title required.');loading('saveSessionBtn',true);const {error}=await sb.from('sessions').insert({user_id:currentUser.id,title,session_date:$('sessionDate').value||today(),duration:$('sessionDuration').value.trim(),objective:$('sessionObjective').value.trim(),setup:$('sessionSetup').value.trim(),coach_points:$('sessionCoachPoints').value.trim()});loading('saveSessionBtn',false);if(error)return alert(error.message);['sessionTitle','sessionDuration','sessionObjective','sessionSetup','sessionCoachPoints'].forEach(id=>$(id).value='');await loadAll()}
async function fetchSessions(){const {data,error}=await sb.from('sessions').select('*').eq('user_id',currentUser.id).order('session_date',{ascending:false});if(error)throw error;sessions=data||[]}
function renderSessions(){$('sessionsList').innerHTML=sessions.map(s=>`<div class="item"><div class="item-row"><div><b>${esc(s.title)}</b><br><small>${s.session_date||''} • ${esc(s.duration||'Duration not set')}</small></div><button class="danger" onclick="deleteRow('sessions','${s.id}')">Delete</button></div>${s.objective?`<p><b>Objective:</b> ${esc(s.objective)}</p>`:''}${s.setup?`<p><b>Setup:</b> ${esc(s.setup)}</p>`:''}${s.coach_points?`<p><b>Coach points:</b> ${esc(s.coach_points)}</p>`:''}</div>`).join('')||'<p class="muted">No sessions saved yet.</p>'}
function renderAttendanceForm(){$('attendanceList').innerHTML=players.map(p=>`<div class="check"><label><input type="checkbox" class="att-check" data-player="${p.id}"> ${esc(nameOf(p.id))}</label><small>${esc(posText(p))}</small></div>`).join('')||'<p class="muted">Add players first.</p>'}
async function saveAttendance(){if(!requireUser())return;const date=$('attendanceDate').value||today(),note=$('attendanceNote').value.trim()||'Training Session';const rows=[...document.querySelectorAll('.att-check')].map(i=>({user_id:currentUser.id,player_id:i.dataset.player,attendance_date:date,present:i.checked,note}));if(!rows.length)return alert('Add players first.');loading('saveAttendanceBtn',true);const {error}=await sb.from('attendance').insert(rows);loading('saveAttendanceBtn',false);if(error)return alert(error.message);await loadAll();alert('Training attendance saved.')}
async function fetchAttendance(){const {data,error}=await sb.from('attendance').select('*').eq('user_id',currentUser.id).order('attendance_date',{ascending:false}).limit(1000);if(error)throw error;attendanceRows=data||[]}
function renderAttendanceHistory(){const groups={};attendanceRows.forEach(r=>{const k=`${r.attendance_date}__${r.note||'Training Session'}`;groups[k]??={date:r.attendance_date,note:r.note||'Training Session',present:[],absent:[]};(r.present?groups[k].present:groups[k].absent).push(nameOf(r.player_id))});const arr=Object.values(groups);$('attendanceHistory').innerHTML=arr.map((g,i)=>`<div class="item clickable"><div class="item-row" onclick="toggleGroup('att-${i}')"><div><b>${esc(g.note)}</b><br><small>${g.date} • ${g.present.length} present • ${g.absent.length} absent</small></div><span class="badge">Tap to view</span></div><div id="att-${i}" class="detail hidden"><div class="two-col"><div><h4>Present</h4>${g.present.map(n=>`<span class="chip good">${esc(n)}</span>`).join('')||'<p>None</p>'}</div><div><h4>Absent</h4>${g.absent.map(n=>`<span class="chip bad">${esc(n)}</span>`).join('')||'<p>None</p>'}</div></div></div></div>`).join('')||'<p class="muted">No training attendance saved yet.</p>'}
function toggleGroup(id){$(id).classList.toggle('hidden')}
function renderRatingsForm(){$('ratingsList').innerHTML=players.map(p=>`<div class="check"><div><b>${esc(nameOf(p.id))}</b><br><small>${esc(posText(p))}</small></div><div class="grid two"><label>Rating<input type="number" min="1" max="10" value="7" class="rating-score" data-player="${p.id}"></label><label>Note<input class="rating-note" data-player="${p.id}" placeholder="Sharp, needs scanning..."></label></div></div>`).join('')||'<p class="muted">Add players first.</p>'}
async function saveRatings(){if(!requireUser())return;const date=$('ratingsDate').value||today(),context=$('ratingsContext').value.trim();const rows=[...document.querySelectorAll('.rating-score')].map(i=>{const pid=i.dataset.player;return{user_id:currentUser.id,player_id:pid,rating_date:date,context,score:Math.max(1,Math.min(10,Number(i.value||1))),note:document.querySelector(`.rating-note[data-player="${pid}"]`)?.value||''}});if(!rows.length)return alert('Add players first.');loading('saveRatingsBtn',true);const {error}=await sb.from('player_ratings').insert(rows);loading('saveRatingsBtn',false);if(error)return alert(error.message);await loadAll();alert('Ratings saved.')}
async function fetchRatings(){const {data,error}=await sb.from('player_ratings').select('*').eq('user_id',currentUser.id).order('rating_date',{ascending:false}).limit(1000);if(error)throw error;ratingRows=data||[]}
function renderRatingsHistory(){$('ratingsHistory').innerHTML=ratingRows.slice(0,100).map(r=>`<div class="item"><div class="item-row"><div><b>${esc(nameOf(r.player_id))}</b><br><small>${r.rating_date} • ${esc(r.context||'No context')}</small></div><div><span class="badge good">${r.score}/10</span><button class="danger" onclick="deleteRow('player_ratings','${r.id}')">Delete</button></div></div>${r.note?`<p>${esc(r.note)}</p>`:''}</div>`).join('')||'<p class="muted">No ratings yet.</p>'}
function renderPitchDiagram(){if(!$('pitchDiagram'))return;const f=$('formationSelect').value||Object.keys(FORMATIONS)[0];const coords=FORMATIONS[f]||[];$('pitchDiagram').innerHTML=`<div class="center-circle"></div><div class="box box-top"></div><div class="box box-bottom"></div>`+coords.map(n=>{const pid=currentLineupAssignments[n.pos]||'';const isSource=moveSourcePosition===n.pos;const isTarget=moveSourcePosition&&moveSourcePosition!==n.pos;const label=pid?nameOf(pid):(moveSourcePosition?'Tap here':'Tap to assign');return `<button type="button" draggable="${pid?'true':'false'}" data-position="${esc(n.pos)}" class="position-node ${pid?'assigned':''} ${isSource?'move-source':''} ${isTarget?'move-target':''}" style="left:${n.x}%;top:${n.y}%" ondragstart="dragStart(event,'${n.pos}')" ondragover="allowDrop(event)" ondrop="dropOnPosition(event,'${n.pos}')" ondragend="dragEnd()" onclick="maybeOpenPlayerPicker('${n.pos}')"><strong>${esc(n.pos)}</strong><span>${esc(label)}</span></button>`}).join('');updateMoveNotice();renderBench()}
function maybeOpenPlayerPicker(pos){if(Date.now()<suppressPickerUntil)return;if(moveSourcePosition){completeTapMove(pos);return}openPlayerPicker(pos)}
function updateMoveNotice(){const el=$('moveModeNotice');if(!el)return;if(moveSourcePosition){el.textContent=`Move mode: ${nameOf(currentLineupAssignments[moveSourcePosition])} from ${moveSourcePosition}. Tap another position to move/swap, or tap the same position to cancel.`;el.classList.remove('hidden')}else el.classList.add('hidden')}
function openPlayerPicker(pos){activePosition=pos;$('pickerTitle').textContent=`Select player for ${pos}`;$('playerPickerSelect').innerHTML=playerOptions(currentLineupAssignments[pos]||'',usedPlayerIds(pos));const btn=$('movePickedPlayerBtn');if(btn)btn.classList.toggle('hidden',!currentLineupAssignments[pos]);$('playerPickerModal').classList.remove('hidden')}
function closePlayerPicker(){$('playerPickerModal').classList.add('hidden');activePosition=null}
function startTapMove(){if(!activePosition||!currentLineupAssignments[activePosition])return;moveSourcePosition=activePosition;closePlayerPicker();suppressPickerUntil=Date.now()+350;renderPitchDiagram()}
function completeTapMove(target){const source=moveSourcePosition;if(!source)return;if(source===target){moveSourcePosition=null;renderPitchDiagram();return}const sourceId=currentLineupAssignments[source],targetId=currentLineupAssignments[target];if(!sourceId){moveSourcePosition=null;renderPitchDiagram();return}currentLineupAssignments[target]=sourceId;if(targetId)currentLineupAssignments[source]=targetId;else delete currentLineupAssignments[source];moveSourcePosition=null;suppressPickerUntil=Date.now()+350;renderPitchDiagram()}
function dragStart(e,pos){moveSourcePosition=null;updateMoveNotice();if(!currentLineupAssignments[pos]){e.preventDefault();return}dragSourcePosition=pos;suppressPickerUntil=Date.now()+700;if(e.dataTransfer){e.dataTransfer.setData('text/plain',pos);e.dataTransfer.effectAllowed='move'}}
function allowDrop(e){e.preventDefault();if(e.dataTransfer)e.dataTransfer.dropEffect='move'}
function dropOnPosition(e,target){e.preventDefault();const source=e.dataTransfer?.getData('text/plain')||dragSourcePosition;if(!source||source===target)return;const sourceId=currentLineupAssignments[source],targetId=currentLineupAssignments[target];if(!sourceId)return;currentLineupAssignments[target]=sourceId;if(targetId)currentLineupAssignments[source]=targetId;else delete currentLineupAssignments[source];dragSourcePosition=null;moveSourcePosition=null;suppressPickerUntil=Date.now()+700;renderPitchDiagram()}
function dragEnd(){dragSourcePosition=null;suppressPickerUntil=Date.now()+500}
function savePickedPlayer(){if(!activePosition)return;const pid=$('playerPickerSelect').value;if(pid){removePlayerFromOtherSlots(pid,activePosition);currentLineupAssignments[activePosition]=pid}closePlayerPicker();renderPitchDiagram()}
function clearPickedPlayer(){if(activePosition)delete currentLineupAssignments[activePosition];closePlayerPicker();renderPitchDiagram()}
function renderBench(bench=null){if(!$('benchList'))return;let selected=Array.isArray(bench)?bench:selectedBenchIds();const starters=starterIds();const seen=new Set();selected=selected.map(id=>{if(!id||starters.has(id)||seen.has(id))return '';seen.add(id);return id});$('benchList').innerHTML=Array.from({length:BENCH_COUNT}).map((_,i)=>{const current=selected[i]||'';const otherBench=new Set(selected.filter((id,idx)=>id&&idx!==i));const exclude=new Set([...starters,...otherBench]);return `<div class="bench-slot"><label>Bench ${i+1}<select class="bench-select" onchange="refreshBenchOptions()">${playerOptions(current,exclude)}</select></label></div>`}).join('')}
function refreshBenchOptions(){renderBench(selectedBenchIds())}
async function saveLineup(){if(!requireUser())return;const opponent=$('lineupOpponent').value.trim();if(!opponent)return alert('Opponent required.');const lineup=currentLineupAssignments;const bench=[...document.querySelectorAll('.bench-select')].map(s=>s.value).filter(Boolean);const starters=Object.values(lineup).filter(Boolean);const duplicateStarter=starters.find((id,idx)=>starters.indexOf(id)!==idx);if(duplicateStarter)return alert(`${nameOf(duplicateStarter)} is selected in the Starting XI more than once.`);const duplicateBench=bench.find((id,idx)=>bench.indexOf(id)!==idx);if(duplicateBench)return alert(`${nameOf(duplicateBench)} is selected on the bench more than once.`);const dup=bench.find(id=>starters.includes(id));if(dup)return alert(`${nameOf(dup)} is already in the starting XI. Remove from bench or choose another player.`);if(Object.keys(lineup).length<11&&!confirm('Starting XI is not full. Save anyway?'))return;loading('saveLineupBtn',true);const {error}=await sb.from('match_day_lineups').insert({user_id:currentUser.id,opponent,match_date:$('lineupDate').value||today(),formation:$('formationSelect').value,lineup,bench,notes:$('lineupNotes').value.trim()});loading('saveLineupBtn',false);if(error)return alert(error.message);$('lineupOpponent').value='';$('lineupNotes').value='';currentLineupAssignments={};await loadAll();renderPitchDiagram();alert('Match Day Lineup saved.')}
async function fetchLineups(){const {data,error}=await sb.from('match_day_lineups').select('*').eq('user_id',currentUser.id).order('match_date',{ascending:false});if(error)throw error;lineups=data||[]}
function renderLineups(){$('lineupsList').innerHTML=lineups.map(l=>{const starters=orderedLineupText(l.lineup,l.formation);const bench=(l.bench||[]).map(pid=>nameOf(pid));return`<div class="item"><div class="item-row"><div><b>${esc(l.formation)} vs ${esc(l.opponent)}</b><br><small>${l.match_date||''} • ${starters.length} starters • ${bench.length} bench</small></div><button class="danger" onclick="deleteRow('match_day_lineups','${l.id}')">Delete</button></div><p><b>Starting XI:</b> ${esc(starters.join(' | ')||'None')}</p><p><b>Bench:</b> ${esc(bench.join(', ')||'None')}</p>${l.notes?`<p><b>Notes:</b> ${esc(l.notes)}</p>`:''}</div>`}).join('')||'<p class="muted">No lineups saved yet.</p>'}
function liveAllPlayerIds(){if(!liveMatch)return[];return Object.keys(liveMatch.players)}
function loadLiveLineup(){const id=$('liveLineupSelect').value;if(!id)return alert('Select a saved lineup first.');const l=lineups.find(x=>x.id===id);if(!l)return alert('Lineup not found.');const starters=Object.values(l.lineup||{}).filter(Boolean);const bench=(l.bench||[]).filter(Boolean);liveMatch={lineupId:l.id,opponent:l.opponent,matchDate:l.match_date||today(),formation:l.formation,lineup:l.lineup||{},bench,scoreFor:Number($('liveScoreFor').value||0),scoreAgainst:Number($('liveScoreAgainst').value||0),status:'Loaded',elapsed:0,substitutions:[],events:[],players:{}};starters.forEach(pid=>{liveMatch.players[pid]={player_id:pid,started:true,onPitch:true,totalSeconds:0,lastOnSecond:0}});bench.forEach(pid=>{if(!liveMatch.players[pid])liveMatch.players[pid]={player_id:pid,started:false,onPitch:false,totalSeconds:0,lastOnSecond:null}});renderLiveMatch()}
function startLive(){if(!liveMatch)return alert('Load a lineup first.');if(liveTimer)return;liveMatch.status=liveMatch.elapsed>=2700?'Second Half':'Live';liveTimer=setInterval(()=>{liveMatch.elapsed++;updateLiveClock()},1000);renderLiveMatch()}
function pauseLive(){if(liveTimer){clearInterval(liveTimer);liveTimer=null}if(liveMatch){liveMatch.status='Paused';renderLiveMatch()}}
function halfTime(){if(!liveMatch)return;if(liveTimer){clearInterval(liveTimer);liveTimer=null}if(liveMatch.elapsed<2700)liveMatch.elapsed=2700;liveMatch.status='Half Time';renderLiveMatch()}
function secondHalf(){if(!liveMatch)return;if(liveMatch.elapsed<2700)liveMatch.elapsed=2700;liveMatch.status='Second Half';startLive()}
function fullTime(){if(!liveMatch)return;if(liveTimer){clearInterval(liveTimer);liveTimer=null}liveMatch.status='Full Time';renderLiveMatch()}
function updateLiveClock(){if(!$('liveClock'))return;$('liveClock').textContent=fmtClock(liveMatch?.elapsed||0);$('liveStatus').textContent=liveMatch?`${liveMatch.status} • ${liveMatch.formation||''} vs ${liveMatch.opponent||''}`:'No live match loaded';if(liveMatch){Object.keys(liveMatch.players).forEach(pid=>{const el=$(`live-min-${pid}`);if(el)el.textContent=`${livePlayerMinute(pid)}'`})}}
function renderLiveMatch(){updateLiveClock();if(!liveMatch){$('livePlayersList').innerHTML='<p class="muted">Load a saved lineup to begin.</p>';return}const onIds=liveAllPlayerIds().filter(pid=>liveMatch.players[pid].onPitch);const offIds=liveAllPlayerIds().filter(pid=>!liveMatch.players[pid].onPitch);$('subOffSelect').innerHTML='<option value="">Player off</option>'+onIds.map(pid=>`<option value="${pid}">${esc(nameOf(pid))}</option>`).join('');$('subOnSelect').innerHTML='<option value="">Player on</option>'+offIds.map(pid=>`<option value="${pid}">${esc(nameOf(pid))}</option>`).join('');$('eventPlayerSelect').innerHTML='<option value="">Select player</option>'+liveAllPlayerIds().map(pid=>`<option value="${pid}">${esc(nameOf(pid))}</option>`).join('');$('subMinute').placeholder=String(liveMinute());$('eventMinute').placeholder=String(liveMinute());$('livePlayersList').innerHTML=liveAllPlayerIds().map(pid=>{const p=liveMatch.players[pid];return`<div class="item minutes-row"><b>${esc(nameOf(pid))}</b><span>${p.started?'Starter':'Bench'}</span><span>${p.onPitch?'On pitch':'Off pitch'}</span><span id="live-min-${pid}" class="minutes-value">${livePlayerMinute(pid)}'</span></div>`}).join('');$('liveSubsList').innerHTML=liveMatch.substitutions.map(s=>`<div class="item"><b>${s.minute}' Substitution</b><p>${esc(nameOf(s.off))} off → ${esc(nameOf(s.on))} on</p></div>`).join('')||'<p class="muted">No substitutions yet.</p>';$('liveEventsList').innerHTML=liveMatch.events.map(e=>`<div class="item"><b><span class="event-pill">${esc(e.type)}</span> ${e.minute}'</b><p>${esc(nameOf(e.player_id))}${e.note?' — '+esc(e.note):''}</p></div>`).join('')||'<p class="muted">No events yet.</p>'}
function addSubstitution(){if(!liveMatch)return alert('Load a lineup first.');const off=$('subOffSelect').value,on=$('subOnSelect').value;if(!off||!on)return alert('Choose player off and player on.');const minute=Number($('subMinute').value||liveMinute());const second=minute*60;const offP=liveMatch.players[off],onP=liveMatch.players[on];if(offP&&offP.onPitch){offP.totalSeconds+=(second-(offP.lastOnSecond??second));offP.onPitch=false;offP.lastOnSecond=null}if(onP){onP.onPitch=true;onP.lastOnSecond=second}liveMatch.substitutions.push({minute,off,on});$('subMinute').value='';renderLiveMatch()}
function addLiveEvent(){if(!liveMatch)return alert('Load a lineup first.');const player_id=$('eventPlayerSelect').value;if(!player_id)return alert('Choose a player.');const type=$('eventType').value,minute=Number($('eventMinute').value||liveMinute()),note=$('eventNote').value.trim();liveMatch.events.push({minute,type,player_id,note});if(type==='Goal')$('liveScoreFor').value=Number($('liveScoreFor').value||0)+1;$('eventMinute').value='';$('eventNote').value='';renderLiveMatch()}
async function saveLiveMatch(){if(!requireUser())return;if(!liveMatch)return alert('Load and manage a match first.');liveMatch.scoreFor=Number($('liveScoreFor').value||0);liveMatch.scoreAgainst=Number($('liveScoreAgainst').value||0);const player_minutes=liveAllPlayerIds().map(pid=>({player_id:pid,name:nameOf(pid),started:!!liveMatch.players[pid].started,minutes:livePlayerMinute(pid)}));const payload={user_id:currentUser.id,lineup_id:liveMatch.lineupId,opponent:liveMatch.opponent,match_date:liveMatch.matchDate,formation:liveMatch.formation,lineup:liveMatch.lineup,bench:liveMatch.bench,score_for:liveMatch.scoreFor,score_against:liveMatch.scoreAgainst,status:liveMatch.status,duration_seconds:liveMatch.elapsed,substitutions:liveMatch.substitutions,events:liveMatch.events,player_minutes};loading('saveLiveMatchBtn',true);const {error}=await sb.from('live_matches').insert(payload);loading('saveLiveMatchBtn',false);if(error)return alert(error.message);await fetchLiveMatches();renderLiveMatches();alert('Live match summary saved.')}
function renderLiveMatches(){if(!$('liveMatchesList'))return;if(!liveMatches.length){if(!$('liveMatchesList').innerHTML)$('liveMatchesList').innerHTML='<p class="muted">No live match summaries saved yet.</p>';return}$('liveMatchesList').innerHTML=liveMatches.map(m=>`<div class="item"><div class="item-row"><div><b>${esc(m.formation)} vs ${esc(m.opponent)}</b><br><small>${m.match_date||''} • ${m.score_for??0}-${m.score_against??0} • ${esc(m.status||'Saved')}</small></div><button class="danger" onclick="deleteRow('live_matches','${m.id}')">Delete</button></div><p><b>Minutes:</b> ${esc((m.player_minutes||[]).map(x=>`${x.name}: ${x.minutes}'`).join(' | ')||'None')}</p><p><b>Events:</b> ${esc((m.events||[]).map(e=>`${e.minute}' ${e.type} ${nameOf(e.player_id)}`).join(' | ')||'None')}</p></div>`).join('')}

async function saveMatch(){if(!requireUser())return;const opponent=$('matchOpponent').value.trim();if(!opponent)return alert('Opponent required.');loading('saveMatchBtn',true);const {error}=await sb.from('match_reports').insert({user_id:currentUser.id,opponent,match_date:$('matchDate').value||today(),score:$('matchScore').value.trim(),positives:$('matchPositives').value.trim(),improvements:$('matchImprove').value.trim(),summary:$('matchSummary').value.trim()});loading('saveMatchBtn',false);if(error)return alert(error.message);['matchOpponent','matchScore','matchPositives','matchImprove','matchSummary'].forEach(id=>$(id).value='');await loadAll()}
async function fetchMatches(){const {data,error}=await sb.from('match_reports').select('*').eq('user_id',currentUser.id).order('match_date',{ascending:false});if(error)throw error;matches=data||[]}
function renderMatches(){$('matchesList').innerHTML=matches.map(m=>`<div class="item"><div class="item-row"><div><b>vs ${esc(m.opponent)}</b><br><small>${m.match_date||''} • ${esc(m.score||'Score not set')}</small></div><button class="danger" onclick="deleteRow('match_reports','${m.id}')">Delete</button></div>${m.positives?`<p><b>Went well:</b> ${esc(m.positives)}</p>`:''}${m.improvements?`<p><b>Improve:</b> ${esc(m.improvements)}</p>`:''}${m.summary?`<p><b>Summary:</b> ${esc(m.summary)}</p>`:''}</div>`).join('')||'<p class="muted">No reports yet.</p>'}
function renderCounts(){$('statPlayers').textContent=players.length;$('statTraining').textContent=new Set(attendanceRows.map(r=>`${r.attendance_date}__${r.note}`)).size;$('statLineups').textContent=lineups.length;$('statReports').textContent=matches.length}
async function loadAll(){if(!requireUser())return;try{await loadProfile();await fetchPlayers();await fetchSessions();await fetchAttendance();await fetchRatings();await fetchLineups();await fetchLiveMatches();await fetchMatches();renderPlayers();renderSessions();renderAttendanceHistory();renderRatingsHistory();renderLineups();renderLiveLineupOptions();renderLiveMatches();renderMatches();renderCounts()}catch(e){console.error(e);alert(e.message||'Something failed. Check Supabase SQL has been run.')}}
document.querySelectorAll('.tab').forEach(t=>t.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active-panel'));t.classList.add('active');$(t.dataset.tab).classList.add('active-panel')}));
$('formationSelect').addEventListener('change',()=>{currentLineupAssignments={};moveSourcePosition=null;renderPitchDiagram()});$('signUpBtn').addEventListener('click',signUp);$('loginBtn').addEventListener('click',login);$('logoutBtn').addEventListener('click',logout);$('refreshBtn').addEventListener('click',loadAll);$('saveProfileBtn').addEventListener('click',saveProfile);$('addPlayerBtn').addEventListener('click',addPlayer);$('saveSessionBtn').addEventListener('click',saveSession);$('saveAttendanceBtn').addEventListener('click',saveAttendance);$('saveRatingsBtn').addEventListener('click',saveRatings);$('saveLineupBtn').addEventListener('click',saveLineup);$('saveMatchBtn').addEventListener('click',saveMatch);$('loadLiveLineupBtn').addEventListener('click',loadLiveLineup);$('startLiveBtn').addEventListener('click',startLive);$('pauseLiveBtn').addEventListener('click',pauseLive);$('halfTimeBtn').addEventListener('click',halfTime);$('secondHalfBtn').addEventListener('click',secondHalf);$('fullTimeBtn').addEventListener('click',fullTime);$('addSubBtn').addEventListener('click',addSubstitution);$('addEventBtn').addEventListener('click',addLiveEvent);$('saveLiveMatchBtn').addEventListener('click',saveLiveMatch);$('savePickedPlayerBtn').addEventListener('click',savePickedPlayer);$('movePickedPlayerBtn').addEventListener('click',startTapMove);$('clearPickedPlayerBtn').addEventListener('click',clearPickedPlayer);$('closePickerBtn').addEventListener('click',closePlayerPicker);$('playerPickerModal').addEventListener('click',e=>{if(e.target.id==='playerPickerModal')closePlayerPicker()});init();
